# -*- coding:utf-8 -*-
# Copyright(C) Huawei Technologies Co.,Ltd. 2023. All rights reserved.

# RC_DIAGNOSIS_NORMAL, Root cluster diagnosis normally
RC_DIAGNOSIS_NORMAL = 10000
# HCCL_SOCKET_FAULT_BASE, HCCL get socket error base
HCCL_SOCKET_FAULT_BASE = 10001
# HCCL_SOCKET_FAULT_SYNC, HCCL get socket error due to Inter-card synchronization
HCCL_SOCKET_FAULT_SYNC = 10002
# HCCL_SOCKET_FAULT_UNKNOWN, HCCL get socket error due to unknown reason
HCCL_SOCKET_FAULT_UNKNOWN = 10003
# HCCL_NOTIFY_FAULT_BASE, HCCL notify wait error base
HCCL_NOTIFY_FAULT_BASE = 10004
# HCCL_NOTIFY_FAULT_SYNC, HCCL notify wait error due to Inter-card synchronization
HCCL_NOTIFY_FAULT_SYNC = 10005
# HCCL_NOTIFY_FAULT_UNKNOWN, HCCL notify wait error due to unknown reason
HCCL_NOTIFY_FAULT_UNKNOWN = 10006
# HCCL_NOTIFY_FAULT_CORE_DUMP, HCCL notify wait error due to core dump
HCCL_NOTIFY_FAULT_CORE_DUMP = 10007
# HCCL_P2P_FAULT_BASE, HCCL get P2P status error base
HCCL_P2P_FAULT_BASE = 10008
# HCCL_P2P_FAULT_SYNC, HCCL get P2P status error due to Inter-card synchronization
HCCL_P2P_FAULT_SYNC = 10009
# HCCL_P2P_FAULT_BASE, HCCL get P2P status error due to unknown reason
HCCL_P2P_FAULT_UNKNOWN = 10010
# HCCL_SDMA_FAULT, HCCL SDMA error
HCCL_SDMA_FAULT = 10011
# HCCL_MEMCPY_FAULT, HCCL Memcpy error
HCCL_MEMCPY_FAULT = 10012
# HCCL_TSDCLIENT_FAULT, HCCL TsdClient error
HCCL_TSDCLIENT_FAULT = 10013
# HEARTBEAT_LOST_ERROR, Heartbeat lost error
HEARTBEAT_LOST_ERROR = 10014
# RC_UNKOWN_ERROR_BASE, RC Unkown error
RC_UNKOWN_ERROR_BASE = 10015
# RC_UNKOWN_ERROR_ONE, RC Unkown error one
RC_UNKOWN_ERROR_ONE = 10016
# RC_UNKOWN_ERROR_TWO, RC Unkown error two
RC_UNKOWN_ERROR_TWO = 10017
# RC_UNKOWN_ERROR_THREE, RC Unkown error three
RC_UNKOWN_ERROR_THREE = 10018
# RC_UNKOWN_ERROR_FOUR, RC Unkown error four
RC_UNKOWN_ERROR_FOUR = 10019
# RC_UNKOWN_ERROR_FIVE, RC Unkown error five
RC_UNKOWN_ERROR_FIVE = 10020
# RC_UNKOWN_ERROR_SIX, RC Unkown error six
RC_UNKOWN_ERROR_SIX = 10021
# SINGLE_CLUSTER_ERROR, Single cluster error
SINGLE_CLUSTER_ERROR = 10022


# KG_DIAGNOSIS_NORMAL, Knowledge graph diagnosis normally
KG_DIAGNOSIS_NORMAL = 20000
# RUNTIME_RESOURCEAPPLY_FAULT, failed to apply for resources
RUNTIME_RESOURCEAPPLY_FAULT = 20001
# RUNTIME_REGISTERED_FAULT, registered resources exceeds the maximum setting
RUNTIME_REGISTERED_FAULT = 20002
# RUNTIME_AICORE_FAULT, failed to execute the AI Core operator
RUNTIME_AICORE_FAULT = 20003
# RUNTIME_AICPU_FAULT, failed to execute the AI Cpu operator
RUNTIME_AICPU_FAULT = 20004
# RUNTIME_MEMASYNCCOPY_FAULT, memory Async Copy Failed
RUNTIME_MEMASYNCCOPY_FAULT = 20005
